### PR TITLE
Allow webgme server to be mounted at non-root path

### PR DESCRIPTION
**Pull request by kecso**
Allowing webgme to be served from non-root path of a website.
Config update:
- client.mountedPath (string) is empty by default, should be a proper sub-path (starts with '/' and do not have the same character at the end)

### CODE REVIEW

**Comment by brollb** [comment]
Is there any chance that some of this could be handled by a reverse proxy like nginx?

**Comment by kecso** [comment]
The thing is that most of the communication is covered by such proxy, on the other hand, the client does make relative calls in some cases where the 'initial' address cannot be used.
Also, there are situations where the server provides an address to the client and that cannot be manipulated with such proxy.

**Comment by brollb** [comment]
That makes sense :+1:

**Comment by pmeijer** [comment]
It's true that a proxy could inject a header with mount info (there might be a standard header for that)  and for the server side code that would be pretty straight forward to extract. Initially we figured that since the clients need to that info too, setting it in the gmeConfig would be the easiest way to synchronize them all.
However now when I think about it, the server could communicate the path in a html tag to the clients. It would be nice not to have to keep the gmeConfig in sync with the proxy.

**Pull request merged**
